name: Automate Workflow
on:
    push:
        branches: [ main ]

jobs:
    linter:
        -   name: Checkout Code
            uses: actions/checkout@v3
        -   name: Setup Java17
            uses: actions/setup-java@v3
            with:
                java-version: '17'
                distribution: 'azul'
        -   uses: gradle/gradle-build-action@v2
            with:
                gradle-version: 8.2
                arguments: spotlessCheck

